kotlinx.collections.immutable.ImmutableList
kotlinx.collections.immutable.ImmutableMap
kotlinx.collections.immutable.ImmutableSet
kotlinx.collections.immutable.PersistentList
kotlinx.collections.immutable.PersistentMap
kotlinx.collections.immutable.PersistentSet

com.merveylcu.marticase.feature.tracking.domain.model.*
